In [1]:
import pandas as pd 
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from keras.utils import np_utils




data = pd.read_csv("Alzheimer's.csv")

#Converted the group to dummy variables
data.loc[data.Group=='Nondemented', 'Group'] = 0
data.loc[data.Group=='Demented', 'Group'] = 1
data.loc[data.Group=='Converted', 'Group'] = 2

#Converted the M/F to dummy variables
data.loc[data.Sex=='M', 'Sex'] = 0
data.loc[data.Sex=='F', 'Sex'] = 1

#ToDo
#Fill in SES and Mini Mental State missing sample values
#Use the mean of that category for the value
# Get rid of SES data 

data

Subject ID         MRI ID Group  Visit  MR Delay Sex Hand  Age  EDUC  SES  \
0    OAS2_0001  OAS2_0001_MR1     0      1         0   0    R   87    14  2.0   
1    OAS2_0001  OAS2_0001_MR2     0      2       457   0    R   88    14  2.0   
2    OAS2_0002  OAS2_0002_MR1     1      1         0   0    R   75    12  NaN   
3    OAS2_0002  OAS2_0002_MR2     1      2       560   0    R   76    12  NaN   
4    OAS2_0002  OAS2_0002_MR3     1      3      1895   0    R   80    12  NaN   
..         ...            ...   ...    ...       ...  ..  ...  ...   ...  ...   
368  OAS2_0185  OAS2_0185_MR2     1      2       842   0    R   82    16  1.0   
369  OAS2_0185  OAS2_0185_MR3     1      3      2297   0    R   86    16  1.0   
370  OAS2_0186  OAS2_0186_MR1     0      1         0   1    R   61    13  2.0   
371  OAS2_0186  OAS2_0186_MR2     0      2       763   1    R   63    13  2.0   
372  OAS2_0186  OAS2_0186_MR3     0      3      1608   1    R   65    13  2.0   

     Mini Mental State  Clinical Dementia Rating  \
0                 27.0                       0.0   
1                 30.0                       0.0   
2                 23.0                       0.5   
3                 28.0                       0.5   
4                 22.0                       0.5   
..                 ...                       ...   
368               28.0                       0.5   
369               26.0                       0.5   
370               30.0                       0.0   
371               30.0                       0.0   
372               30.0                       0.0   

     Estimated total Intracranial Volume  Normalize Whole Brain Volume  \
0                                   1987                         0.696   
1                                   2004                         0.681   
2                                   1678                         0.736   
3                                   1738                         0.713   
4                                   1698                         0.701   
..                                   ...                           ...   
368                                 1693                         0.694   
369                                 1688                         0.675   
370                                 1319                         0.801   
371                                 1327                         0.796   
372                                 1333                         0.801   

     Atlas Scaling Factor  
0                   0.883  
1                   0.876  
2                   1.046  
3                   1.010  
4                   1.034  
..                    ...  
368                 1.037  
369                 1.040  
370                 1.331  
371                 1.323  
372                 1.317  

[373 rows x 15 columns]

In [2]:
#PCA might be a good technique to select predictors 

#note that PCA performs best when data is normalized (range b/w 0 and 1)

#It is possible to use categorical and continuous predictors 
#for a regression problem. My understanding is you need to make 
#dummy variables for the binary predictors. 

#Variables that we will need to deal with: 
# Hand, Visit, Subject ID, MRI ID

In [3]:
#Attempting PCA on data
#Hand is completely useless as it is identical for all samples
data_drop = data.drop(['Hand','Visit','Subject ID','MRI ID'], axis = 1) #axis = 1 means to drop column not row

#get rid of row 360 and 359 bc they are missing alot of data (both SES and MMS)
data_drop = data_drop.drop([360, 359])


#delete all data points that dont have SES in them (this is where they have NaN)
data_drop = data_drop.dropna()

#dementia status is what we want to predict - change this to single target 
group = data_drop[['Group']] 



data_drop = data_drop.drop(['Group'], axis = 1) #axis = 1 means to drop column not row




In [4]:
#get a list of columns in pandas object 
names_of_data = data_drop.columns.tolist()

#shuffle = false prevents data split being different everytime
X_train, X_test, y_train, y_test = train_test_split(data_drop, group, test_size=0.2, shuffle = False)

#split test into validate and test, again making sure the data is always the same for consistency
#X_test, X_val, y_test, y_val = train_test_split(X_train, y_train, test_size=0.25, shuffle = False)

#Normalizing the data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#running the actual PCA
from sklearn.decomposition import PCA

pca = PCA()
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)


y_train = y_train.astype('int')
y_test = y_test.astype('int')


from sklearn.neighbors import KNeighborsClassifier
accuracy = list()

#Find which one gets the highest accuracy
for K in range(1,30):
    #K = K+1
    classifier = KNeighborsClassifier(n_neighbors = K)

    classifier.fit(X_train, y_train)  #fit the model
    y_pred = classifier.predict(X_test)
    

    accuracy.append(accuracy_score(y_test,y_pred)) #store rmse values
    print('accuracy value for k= ' , K , 'is:', accuracy[K-1])
    
max_value = max(accuracy)
best_k_value = accuracy.index(max_value) + 1
print(best_k_value)
classifier = KNeighborsClassifier(n_neighbors=best_k_value)
classifier.fit(X_train, y_train) 
#relief f algorithm - sorting features 

accuracy value for k=  1 is: 0.7605633802816901
accuracy value for k=  2 is: 0.7746478873239436
accuracy value for k=  3 is: 0.7746478873239436
accuracy value for k=  4 is: 0.7887323943661971
accuracy value for k=  5 is: 0.7605633802816901
accuracy value for k=  6 is: 0.7605633802816901
accuracy value for k=  7 is: 0.7605633802816901
accuracy value for k=  8 is: 0.7605633802816901
accuracy value for k=  9 is: 0.7605633802816901
accuracy value for k=  10 is: 0.7605633802816901
accuracy value for k=  11 is: 0.7605633802816901
accuracy value for k=  12 is: 0.7605633802816901
accuracy value for k=  13 is: 0.7464788732394366
accuracy value for k=  14 is: 0.7605633802816901
accuracy value for k=  15 is: 0.7746478873239436
accuracy value for k=  16 is: 0.7605633802816901
accuracy value for k=  17 is: 0.7605633802816901
accuracy value for k=  18 is: 0.7605633802816901
accuracy value for k=  19 is: 0.7464788732394366
accuracy value for k=  20 is: 0.7464788732394366
accuracy value for k=  21 is:

/Users/RJ/Desktop/mypython/lib/python3.7/site-packages/ipykernel_launcher.py:36: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
/Users/RJ/Desktop/mypython/lib/python3.7/site-packages/ipykernel_launcher.py:36: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
/Users/RJ/Desktop/mypython/lib/python3.7/site-packages/ipykernel_launcher.py:36: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
/Users/RJ/Desktop/mypython/lib/python3.7/site-packages/ipykernel_launcher.py:36: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
/Users/RJ/Desktop/mypython/lib/python3.7/site-packag

KNeighborsClassifier(n_neighbors=4)

In [5]:
pd.set_option("display.max_rows", None, "display.max_columns", None)


display(y_train)

y_pred

Group
0        0
1        0
5        0
6        0
7        0
8        0
9        0
13       0
14       0
15       1
16       1
17       1
18       1
19       0
20       0
21       0
22       0
23       0
24       0
25       1
26       1
27       1
28       1
29       0
30       0
31       0
32       0
33       2
34       2
35       2
36       2
37       2
38       2
39       1
40       1
41       0
42       0
43       1
44       1
45       1
46       1
47       0
48       0
49       0
50       0
51       1
52       1
53       0
54       0
55       0
56       0
57       2
58       2
59       2
60       1
61       1
62       0
63       0
64       0
65       0
66       0
67       0
68       0
69       0
70       0
71       0
72       1
73       1
74       1
75       1
76       1
77       1
78       1
79       1
80       1
81       2
82       2
83       2
84       0
85       0
86       1
87       1
88       1
89       1
90       1
91       0
92       0
93       1
94       1
95       0
96       0
97       1
98       1
99       1
100      1
101      1
102      0
103      0
104      0
105      1
106      1
107      0
108      0
109      0
110      0
111      0
112      0
113      0
114      2
115      2
116      0
117      0
118      0
119      0
120      0
121      0
122      0
123      1
124      1
125      1
126      1
127      1
128      0
129      0
130      0
131      0
132      0
133      0
136      1
137      1
138      1
139      1
140      1
141      0
142      0
143      0
144      0
145      0
146      0
147      0
148      0
149      0
150      0
151      0
152      0
153      0
154      1
155      1
156      0
157      0
158      0
159      0
160      0
161      1
162      1
163      0
164      0
165      0
166      0
167      0
168      0
169      0
170      0
171      1
172      1
173      1
174      1
175      1
176      1
177      1
178      1
179      0
180      0
181      0
182      0
183      1
184      1
185      1
186      1
187      1
188      1
189      0
190      0
191      0
192      0
193      0
194      2
195      2
196      0
197      0
198      0
199      0
200      0
201      0
202      0
203      0
204      0
205      1
206      1
209      0
210      0
211      0
212      0
213      0
214      0
215      1
216      1
217      1
218      2
219      2
220      2
221      1
222      1
223      0
224      0
225      1
226      1
227      1
228      1
229      0
230      0
231      1
232      1
233      1
234      1
235      1
236      1
239      1
240      1
241      0
242      0
243      0
244      0
245      2
246      2
247      0
248      0
249      0
250      1
251      1
252      0
253      0
254      0
255      0
256      1
257      1
258      0
259      0
260      0
261      2
262      2
263      2
264      2
265      2
266      0
267      0
268      0
269      0
270      0
271      2
272      2
273      2
274      2
275      1
276      1
277      0
278      0
279      1
280      1
281      0
282      0
283      1
284      1
285      1
286      1
287      1
288      0
289      0
290      0
291      0
292      0
293      0
294      0

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0])

In [6]:
y_pred = classifier.predict(X_test)


from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
results = classification_report(y_test, y_pred)
results[0]

accuracy_score(y_test,y_pred)

[[38  0  0]
 [ 5 17  4]
 [ 3  3  1]]
              precision    recall  f1-score   support

           0       0.83      1.00      0.90        38
           1       0.85      0.65      0.74        26
           2       0.20      0.14      0.17         7

    accuracy                           0.79        71
   macro avg       0.63      0.60      0.60        71
weighted avg       0.77      0.79      0.77        71



0.7887323943661971